require("config/plugins")
require("config/keybindings")
require("config/settings")
require("colorloaders/colors")
require("config/autocommands")
require("config/buffers")
require("config/comments")
require("config/completion")
require("config/git")
require("config/julia")
require("config/latex")
require("config/lsp")
-- require("config/lualine")
require("config/markdown")
require("config/search")
require("config/snippets")
require("config/terminal")
require("config/todo")
require("config/tree")
require("config/treesitter")
require("config/trouble")
require("config/zettels")

vim.cmd("set laststatus=0")
-- vim.cmd("set winbar=%=%m\\ %f")
