require("config/plugins")
require("config/keybindings")
require("config/settings")
require("config/colors/colors")
require("config/autocommands")
-- require("config/bufferline")
require("config/buffers")
require("config/comments")
require("config/completion")
require("config/git")
require("config/headlines")
require("config/julia")
require("config/latex")
require("config/leap")
require("config/lsp")
require("config/lualine")
require("config/markdown")
require("config/search")
require("config/snippets")
require("config/terminal")
require("config/todo")
require("config/tree")
require("config/treesitter")
require("config/trouble")
require("config/zettels")

-- vim.cmd("set winbar=%=%m\\ %f")
