pcall(require, "config/plugins")
pcall(require, "config/keybindings")
pcall(require, "config/settings")
pcall(require, "colorloaders/colors")

pcall(require, "config/autocommands")
pcall(require, "config/buffers")
pcall(require, "config/comments")
-- pcall(require, "config/completion")
require("config/completion")
pcall(require, "config/git")
pcall(require, "config/julia")
pcall(require, "config/latex")
pcall(require, "config/lsp")
-- pcall(require, "config/lualine")
pcall(require, "config/search")
-- pcall(require, "config/snippets")
require("config/snippets")
pcall(require, "config/terminal")
pcall(require, "config/todo")
pcall(require, "config/tree")
pcall(require, "config/treesitter")
pcall(require, "config/trouble")
pcall(require, "config/zettels")
-- pcall(require, "config/copilot")

vim.cmd("set laststatus=0")
-- vim.cmd("set winbar=%=%m\\ %f")
