vim.o.autoindent = true
vim.o.autoread = true
vim.o.breakindent = true
-- vim.o.ch = 0
vim.o.cindent = true
vim.o.clipboard = "unnamedplus"
vim.o.cursorline = true
vim.o.encoding = "UTF-8"
vim.o.expandtab = true
vim.o.foldenable = false
vim.o.hidden = true
vim.o.ignorecase = true
vim.o.incsearch = true
vim.o.linebreak = true
-- vim.o.ls = 0
vim.o.mouse = "a"
vim.o.number = true
-- vim.o.numberwidth = 2
-- vim.o.relativenumber = true
vim.o.shiftwidth = 4
vim.o.showbreak = "↪ "
vim.o.signcolumn = "yes"
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.spell = false
vim.o.spelllang = "en_us"
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.tabstop = 4
vim.o.textwidth = 79
vim.o.timeoutlen = 500
vim.o.title = true
vim.o.updatetime = 300
-- vim.o.winblend = 10
-- vim.o.wrap = true
vim.o.showmode = false

vim.g.editorconfig = true
vim.g.formatdef_latexindent = "'latexindent -'"
vim.g.formatdef_python = "black"
vim.g.loaded_perl_provider = false
vim.g.python3_host_prog = "/usr/bin/python"
