vim.o.autoindent = true
vim.o.autoread = true
vim.o.breakindent = true
vim.o.ch = 0
vim.o.cindent = true
vim.o.clipboard = "unnamedplus"
vim.o.conceallevel = 2
vim.o.cursorline = true
vim.o.encoding = "UTF-8"
vim.o.expandtab = true
vim.o.foldmethod = "expr"
-- vim.o.foldexpr = "nvim_treesitter#foldexpr()"
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
-- vim.o.foldtext = "v:lua.vim.treesitter.foldtext()"
vim.o.foldtext = ""
vim.o.fillchars = "fold: "
vim.o.foldenable = false
vim.o.hidden = true
vim.o.ignorecase = true
vim.o.incsearch = true
vim.o.laststatus = 3
vim.o.linebreak = true
vim.o.mouse = "a"
vim.o.number = true
-- vim.o.numberwidth = 2
-- vim.o.relativenumber = true
vim.o.scrolloff = 3
vim.o.shiftwidth = 4
vim.o.showbreak = "↪ "
vim.o.signcolumn = "yes"
-- vim.o.signcolumn = "auto"
-- vim.o.signcolumn = "auto:2"
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.spell = false
vim.o.spelllang = "en_us"
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.tabstop = 4
vim.o.termguicolors = true
vim.o.textwidth = 80
vim.o.timeoutlen = 500
vim.o.title = true
vim.o.undofile = true
-- vim.o.updatetime = 300
vim.o.updatetime = 50
-- vim.o.winblend = 10
-- vim.o.wrap = true
vim.o.showmode = false
-- vim.o.wildmode = "longest:full,full" -- Command-line completion mode

vim.g.editorconfig = true
vim.g.formatdef_latexindent = "'latexindent -'"
vim.g.formatdef_python = "black"
vim.g.loaded_perl_provider = false
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.netrw_keepdir = false
vim.g.netrw_banner = false
vim.g.python3_host_prog = "/usr/bin/python"
vim.g.winbar = true

-- -- Remove window separators
-- vim.cmd([[:set fillchars+=horiz:\ ]])
-- vim.cmd([[:set fillchars+=horizup:\ ]])
-- vim.cmd([[:set fillchars+=horizdown:\ ]])
-- vim.cmd([[:set fillchars+=vert:\ ]])
-- vim.cmd([[:set fillchars+=vertleft:\ ]])
-- vim.cmd([[:set fillchars+=vertright:\ ]])
-- vim.cmd([[:set fillchars+=verthoriz:\ ]])
